GET https://api.poloniex.com/markets/BCH_USDT/candles?interval=MINUTE_1
HTTP 200

GET https://api.poloniex.com/markets/BCH_USDT/candles?interval=MINUTE_15
HTTP 200

GET https://api.poloniex.com/markets/BCH_USDT/candles?interval=HOUR_1
HTTP 200

GET https://api.poloniex.com/markets/BCH_USDT/candles?interval=DAY_1
HTTP 200

GET https://api.poloniex.com/markets/BTC_USDT/candles?interval=MINUTE_1
HTTP 200

GET https://api.poloniex.com/markets/BTC_USDT/candles?interval=MINUTE_15
HTTP 200

GET https://api.poloniex.com/markets/BTC_USDT/candles?interval=HOUR_1
HTTP 200

GET https://api.poloniex.com/markets/BTC_USDT/candles?interval=DAY_1
HTTP 200

GET https://api.poloniex.com/markets/DOGE_USDT/candles?interval=MINUTE_1
HTTP 200

GET https://api.poloniex.com/markets/DOGE_USDT/candles?interval=MINUTE_15
HTTP 200

GET https://api.poloniex.com/markets/DOGE_USDT/candles?interval=HOUR_1
HTTP 200

GET https://api.poloniex.com/markets/DOGE_USDT/candles?interval=DAY_1
HTTP 200

GET https://api.poloniex.com/markets/ETH_USDT/candles?interval=MINUTE_1
HTTP 200

GET https://api.poloniex.com/markets/ETH_USDT/candles?interval=MINUTE_15
HTTP 200

GET https://api.poloniex.com/markets/ETH_USDT/candles?interval=HOUR_1
HTTP 200

GET https://api.poloniex.com/markets/ETH_USDT/candles?interval=DAY_1
HTTP 200

GET https://api.poloniex.com/markets/TRX_USDT/candles?interval=MINUTE_1
HTTP 200

GET https://api.poloniex.com/markets/TRX_USDT/candles?interval=MINUTE_15
HTTP 200

GET https://api.poloniex.com/markets/TRX_USDT/candles?interval=HOUR_1
HTTP 200

GET https://api.poloniex.com/markets/TRX_USDT/candles?interval=DAY_1
HTTP 200
